from backend.agents.coordinator import Plan
from backend.agents.rag_agents import ListSubQuery
from typing import TypedDict, List, Optional, Dict, Any, Annotated, Literal
from langchain_core.documents import Document
from langgraph.graph import StateGraph
"""
-----------------------State Update Protocols----------------------
1. Xác định chính xác tác vụ đang làm:

    Đọc current_task_id từ State, sau đó tìm trong plan để 
    lấy đúng instruction và args 
    phục vụ cho việc thực thi.

2. Đánh dấu hoàn thành (Thành công):

    Sau khi chạy xong logic của node (truy vấn ChromaDB, viết email,...), 
    node phải lấy danh sách completed_tasks hiện tại, thêm current_task_id vào đó, 
    và trả về để ghi đè lên State. 
    Nếu không làm vậy, router_node sẽ đọc lại plan
    và tiếp tục bắt chạy lại chính task vừa làm.

3. Đánh dấu lỗi (Thất bại):

    Mọi logic thực thi nên được bọc trong try...except. 
    Nếu có lỗi xảy ra (ví dụ: API LLM sập, lỗi kết nối DB), 
    node phải ném current_task_id vào failed_tasks. 
    Nhờ vậy, router_node sẽ biết tác vụ này hỏng và bỏ qua nó để đi tới tác vụ tiếp theo 
    (hoặc về GENERAL_CHAT).

Sample: một node xử lý tác vụ

    def rag_search_node(state: GraphState):
        task_id = state["current_task_id"]
        task = state["plan"].tasks[task_id]

        print(f"Đang chạy task {task_id}: {task.instruction}")

        # xử lý logic...

        return {
            "completed_tasks": state.get("completed_tasks", []) + [task_id]
        }


"""

def get_next_task(plan, completed, failed):
    for task_id in sorted(plan.tasks.keys()):
        task = plan.tasks[task_id]

        if task_id in completed or task_id in failed:
            continue

        # check dependencies
        if all(dep in completed for dep in task.dependencies):
            return task

    return None

class GraphState(TypedDict):
    """
    Global shared state across the entire LangGraph workflow.

    Each field represents a piece of data produced or consumed
    by different nodes in the pipeline.
    """

    # =========================================================
    # USER INPUT
    # =========================================================

    user_input: Annotated[
        str,
        "Original request from the HR user that starts the workflow."
    ]


    # =========================================================
    # EXECUTION CONTROL
    # =========================================================

    plan: Annotated[
        Optional["Plan"],
        "Execution plan generated by the Manager Agent containing ordered tasks."
    ]

    current_task_id: Annotated[
        Optional[int],
        "ID of the task currently being executed in the plan."
    ]

    current_route: Annotated[
        Literal["RAG_SEARCH", "WRITE_EMAIL", "GENERATE_INTERVIEW_BRIEF" , "GENERAL_CHAT"],
        "Route name indicating which module should execute the current task."
    ]

    completed_tasks: Annotated[
        Optional[List[int]],
        "List of task IDs that have successfully completed execution."
    ]

    failed_tasks: Annotated[
        Optional[List[int]],
        "List of task IDs that failed during execution."
    ]

    # =========================================================
    # RAG PIPELINE DATA
    # =========================================================

    search_queries: Annotated[
        Optional[ListSubQuery],
        "List query rewritten by the LLM to optimize retrieval from the vector database."
    ]

    cv_documents: Annotated[
        Optional[List[Document]],
        "CVs documents retrieved."
    ]

    history_cv_store: Annotated[
        Optional[Dict],
        "CVs documents retrieved from the previous query."
    ]

    company_documents: Annotated[
        Optional[List[Document]],
        "Company documents retrieved."
    ]

    company_compressed_context: Annotated[
        Optional[str],
        "Ngữ cảnh đã được nén bằng Map-Reduce từ các tài liệu truy xuất được. Chỉ sử dụng cho company documents"
    ]

    # =========================================================
    # MODULE OUTPUTS
    # =========================================================

    # ----- Email Module -----

    email_draft: Annotated[
        Optional[str],
        "Draft email generated by the email module before user confirmation."
    ]

    email_sent: Annotated[
        Optional[bool],
        "Indicates whether the email was successfully sent."
    ]


    # ----- Interview Brief Module -----

    interview_brief: Annotated[
        Optional[str],
        "Generated structured interview preparation content."
    ]

    interview_pdf_path: Annotated[
        Optional[str],
        "Filesystem path to the generated interview brief PDF."
    ]


    # ----- Generic Outputs -----

    module_outputs: Annotated[
        Optional[Dict[str, Any]],
        "Flexible storage for outputs from modules that do not have dedicated fields."
    ]


    # =========================================================
    # FINAL RESPONSE
    # =========================================================

    final_answer: Annotated[
        Optional[str],
        "Final response synthesized by the Response Agent and returned to the user."
    ]

workflow = StateGraph(GraphState)