from backend.agents.coordinator import Plan
from typing import TypedDict, List, Optional, Dict, Any, Annotated, Literal
from langgraph.graph import StateGraph, START, END
from langgraph.checkpoint.memory import InMemorySaver
from langchain_core.documents import Document
from backend.agents.coordinator import manager_agent, response_agent

import time
from langchain_core.documents import Document

memory = InMemorySaver()
# Sau này sẽ sử dụng Dùng SqliteSaver hoặc DB tương tự

class GraphState(TypedDict):
    """
    Global shared state across the entire LangGraph workflow.

    Each field represents a piece of data produced or consumed
    by different nodes in the pipeline.
    """

    # =========================================================
    # USER INPUT
    # =========================================================

    user_query: Annotated[
        str,
        "Original request from the HR user that starts the workflow."
    ]


    # =========================================================
    # EXECUTION CONTROL
    # =========================================================

    plan: Annotated[
        Optional["Plan"],
        "Execution plan generated by the Manager Agent containing ordered tasks."
    ]

    current_task_id: Annotated[
        Optional[int],
        "ID of the task currently being executed in the plan."
    ]

    current_route: Annotated[
        Literal["RAG_SEARCH", "WRITE_EMAIL", "GENERATE_INTERVIEW_BRIEF" , "GENERAL_CHAT"],
        "Route name indicating which module should execute the current task."
    ]

    completed_tasks: Annotated[
        Optional[List[int]],
        "List of task IDs that have successfully completed execution."
    ]

    failed_tasks: Annotated[
        Optional[List[int]],
        "List of task IDs that failed during execution."
    ]

    # =========================================================
    # RAG PIPELINE DATA
    # =========================================================

    search_query: Annotated[
        Optional[str],
        "Query rewritten by the LLM to optimize retrieval from the vector database."
    ]

    documents: Annotated[
        Optional[List[Document]],
        "Raw documents retrieved from the vector database (CVs, policies, etc.)."
    ]

    filtered_documents: Annotated[
        Optional[List[Document]],
        "Documents remaining after filtering or grading for relevance."
    ]


    # =========================================================
    # MODULE OUTPUTS
    # =========================================================

    # ----- Email Module -----

    email_draft: Annotated[
        Optional[str],
        "Draft email generated by the email module before user confirmation."
    ]

    email_sent: Annotated[
        Optional[bool],
        "Indicates whether the email was successfully sent."
    ]


    # ----- Interview Brief Module -----

    interview_brief: Annotated[
        Optional[str],
        "Generated structured interview preparation content."
    ]

    interview_pdf_path: Annotated[
        Optional[str],
        "Filesystem path to the generated interview brief PDF."
    ]


    # ----- Generic Outputs -----

    module_outputs: Annotated[
        Optional[Dict[str, Any]],
        "Flexible storage for outputs from modules that do not have dedicated fields."
    ]


    # =========================================================
    # FINAL RESPONSE
    # =========================================================

    final_answer: Annotated[
        Optional[str],
        "Final response synthesized by the Response Agent and returned to the user."
    ]


def manager_node(state: GraphState):
    print("\n-> Manager agent đang phân chia công việc!")
    response = manager_agent.invoke({"user_query": state["user_query"]})
    return {"plan": response}

def router_node(state: GraphState):
    """
    Các trường mà node tác động:
        1. plan : Chỉ đọc
        2. current_task_id: Gắn id cho task chuẩn bị được thực thi. 
        3. current_route: Gắn tên route cho task dang chuẩn bị được thực thi 
        4. completed_tasks: id của các nhiệm vụ đã hoàn thành
        5. failed_tasks: id của các nhiệm vụ hoàn thành với lỗi

    Công việc: Đọc plan và chuyển hướng theo danh sách nhiệm vụ đã đề ra
    Trong trường hợp số lượng nhiệm vụ bằng 0, gán trường current_route là GENERAL_CHAT

    """

    plan = state.get("plan")
    completed_tasks = state.get("completed_tasks", [])
    failed_tasks = state.get("failed_tasks", [])

    # Nếu plan rỗng (yêu cầu chung chung)
    if not plan or not plan.tasks:
        return {
            "current_route": "GENERAL_CHAT",
            "current_task_id": None
        }

    # Tìm task đầu tiên chưa được thực hiện
    next_task = None
    for task in plan.tasks:
        if task.task_id not in completed_tasks and task.task_id not in failed_tasks:
            next_task = task
            break

    # Nếu tìm thấy task cần làm tiếp theo
    if next_task:
        return {
            "current_route": next_task.route,
            "current_task_id": next_task.task_id
        }
    
    # Nếu vòng lặp kết thúc mà không có next_task -> Tất cả task đã xong
    return {
        "current_route": "GENERAL_CHAT",
        "current_task_id": None
    }



def route_condition(state: GraphState) -> str:
    """Hàm này đọc state và trả về TÊN NODE tiếp theo cần chạy"""
    route = state.get("current_route")
    
    if route == "RAG_SEARCH":
        return "rag_search_node"
    
    elif route == "WRITE_EMAIL":
        return "write_email_node"
    
    elif route == "GENERATE_INTERVIEW_BRIEF":
        return "generate_interview_brief_node"

    else:
        return "general_chat_node"

"""
---------------------------------------------State Update Protocol-----------------------------------------
1. Xác định chính xác tác vụ đang làm:

    Đọc current_task_id từ State, sau đó tìm trong plan để lấy đúng instruction và args 
    phục vụ cho việc thực thi.

2. Đánh dấu hoàn thành (Thành công):

    Sau khi chạy xong logic của node (truy vấn ChromaDB, viết email,...), 
    node phải lấy danh sách completed_tasks hiện tại, thêm current_task_id vào đó, 
    và trả về để ghi đè lên State. 
    Nếu không làm vậy, router_node sẽ đọc lại plan và tiếp tục bắt chạy lại chính task vừa làm.

3. Đánh dấu lỗi (Thất bại):

    Mọi logic thực thi nên được bọc trong try...except. 
    Nếu có lỗi xảy ra (ví dụ: API LLM sập, lỗi kết nối DB), 
    node phải ném current_task_id vào failed_tasks. 
    Nhờ vậy, router_node sẽ biết tác vụ này hỏng và bỏ qua nó để đi tới tác vụ tiếp theo 
    (hoặc về GENERAL_CHAT).


def rag_search_node(state: GraphState):
    pass # sẽ viết sau

def write_email_node(state: GraphState):
    pass # sẽ viết sau

def generate_interview_brief_node(state: GraphState):
    pass # sẽ viết sau



"""
def general_chat_node(state: GraphState):
    print("Agent đang trả về kết quả cuói cùng!")
    response = response_agent.invoke(state)
    return {"final_answer": response}

# Fake node để debug

def rag_search_node(state: GraphState):
    current_task_id = state.get("current_task_id")
    plan = state.get("plan")
    completed_tasks = state.get("completed_tasks", []) or []
    failed_tasks = state.get("failed_tasks", []) or []

    # 1. Tìm task hiện tại
    current_task = next((t for t in plan.tasks if t.task_id == current_task_id), None)
    if not current_task:
        return {"failed_tasks": failed_tasks + [current_task_id]}

    try:
        # 2. Mock quá trình thực thi
        print(f"\n[RAG_SEARCH_NODE] Đang thực thi Task {current_task_id}...")
        print(f"   -> Chỉ thị: {current_task.instruction}")
        print(f"   -> Đang tìm kiếm trong Vector Database (giả lập mất 2s)...")
        time.sleep(2)

        # Tạo dữ liệu giả
        mock_docs = [
            Document(page_content="CV Nguyễn Văn A: 5 năm kinh nghiệm Java, Spring Boot.", metadata={"source": "cv_nguyen_van_a.pdf"}),
            Document(page_content="CV Trần Thị B: 3 năm kinh nghiệm Python, AI/ML.", metadata={"source": "cv_tran_thi_b.pdf"})
        ]

        print(f"   -> [THÀNH CÔNG] Đã tìm thấy {len(mock_docs)} tài liệu.")

        # 3. Cập nhật State
        return {
            "completed_tasks": completed_tasks + [current_task_id],
            "documents": mock_docs, # Ghi đè tài liệu thô
            "filtered_documents": mock_docs # Ở mock thì coi như filter xong luôn
        }

    except Exception as e:
        # 4. Ghi nhận lỗi
        print(f"   -> [THẤT BẠI] Task {current_task_id} gặp lỗi: {e}")
        return {"failed_tasks": failed_tasks + [current_task_id]}


def write_email_node(state: GraphState):
    current_task_id = state.get("current_task_id")
    plan = state.get("plan")
    completed_tasks = state.get("completed_tasks", []) or []
    failed_tasks = state.get("failed_tasks", []) or []

    current_task = next((t for t in plan.tasks if t.task_id == current_task_id), None)
    if not current_task:
        return {"failed_tasks": failed_tasks + [current_task_id]}

    try:
        print(f"\n[WRITE_EMAIL_NODE] Đang thực thi Task {current_task_id}...")
        print(f"   -> Nguồn dữ liệu sử dụng: {current_task.data_source}")
        print(f"   -> Đang soạn email (giả lập mất 1s)...")
        time.sleep(1)

        # Lấy thử doc từ state xem có dữ liệu không
        docs = state.get("filtered_documents", [])
        num_candidates = len(docs) if docs else 0

        mock_email = f"""
        Kính gửi các ứng viên ({num_candidates} người),
        Chúng tôi rất ấn tượng với hồ sơ của bạn và muốn mời bạn tham gia vòng phỏng vấn tiếp theo.
        Trân trọng, HR Team.
        """

        print(f"   -> [THÀNH CÔNG] Đã tạo và gửi draft email.")

        return {
            "completed_tasks": completed_tasks + [current_task_id],
            "email_draft": mock_email.strip(),
            "email_sent": True
        }

    except Exception as e:
        print(f"   -> [THẤT BẠI] Task {current_task_id} gặp lỗi: {e}")
        return {"failed_tasks": failed_tasks + [current_task_id]}


def generate_interview_brief_node(state: GraphState):
    current_task_id = state.get("current_task_id")
    plan = state.get("plan")
    completed_tasks = state.get("completed_tasks", []) or []
    failed_tasks = state.get("failed_tasks", []) or []

    current_task = next((t for t in plan.tasks if t.task_id == current_task_id), None)
    if not current_task:
        return {"failed_tasks": failed_tasks + [current_task_id]}

    try:
        print(f"\n[INTERVIEW_BRIEF_NODE] Đang thực thi Task {current_task_id}...")
        print(f"   -> Chỉ thị: {current_task.instruction}")
        print(f"   -> Đang tổng hợp báo cáo phỏng vấn (giả lập mất 2s)...")
        time.sleep(2)

        mock_brief = "TÓM TẮT PHỎNG VẤN:\n- Ứng viên phù hợp với tiêu chí chuyên môn.\n- Đề xuất câu hỏi: 'Hãy kể về dự án khó nhất bạn từng làm?'"
        mock_path = "/mock/path/to/interview_brief_01.pdf"

        print(f"   -> [THÀNH CÔNG] Đã tạo file tóm tắt phỏng vấn.")

        return {
            "completed_tasks": completed_tasks + [current_task_id],
            "interview_brief": mock_brief,
            "interview_pdf_path": mock_path
        }

    except Exception as e:
        print(f"   -> [THẤT BẠI] Task {current_task_id} gặp lỗi: {e}")
        return {"failed_tasks": failed_tasks + [current_task_id]}



#----------------------------------------------------
# Gắn Node và Edge
workflow = StateGraph(GraphState)

workflow.add_node("manager_node", manager_node)
workflow.add_node("router_node", router_node)

workflow.add_node("rag_search_node", rag_search_node)
workflow.add_node("write_email_node", write_email_node)
workflow.add_node("generate_interview_brief_node", generate_interview_brief_node)
workflow.add_node("general_chat_node", general_chat_node)


workflow.add_edge(START, "manager_node")
workflow.add_edge("manager_node", "router_node")
workflow.add_conditional_edges("router_node", route_condition, 
    {
        "rag_search_node":                "rag_search_node",
        "write_email_node":               "write_email_node",
        "generate_interview_brief_node":  "generate_interview_brief_node",
        "general_chat_node":              "general_chat_node"
    }
)

workflow.add_edge("rag_search_node", "router_node")
workflow.add_edge("write_email_node", "router_node")
workflow.add_edge("generate_interview_brief_node", "router_node")

workflow.add_edge("general_chat_node", END)


# Biên dịch và chạy dồ thị

app = workflow.compile(checkpointer= memory)

user_input = {"user_query": str(input("Chào Hr! Bạn có yêu cầu gì cho tôi?\n"))}

config = {"configurable": {"thread_id": "1"}} 
result = app.invoke(user_input, config=config)

# Nên cho phản hồi .stream()
print(result["final_answer"])

# run: python -m backend.graphs.main_graph
# Tìm cho tôi 2 CV Java và gửi email phỏng vấn cho họ
